version: "3.9"
services:
  database:
    image: mysql:8.0.27
    container_name: user_management_mysql
    volumes:
      - user_management_mysql_volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: user_management_admin
    networks:
      - user_management_networks
    ports:
      - "3306:3306"
networks:
  user_management_networks:
volumes:
  user_management_mysql_volume: