spring:
  datasource:
    user-management:
      url: jdbc:mysql://localhost:3306/user_management
      username: root
      password: 123456
      driverClassName: com.mysql.cj.jdbc.Driver
      max-active: 500
      max-idle: 20
      initial-size: 20