spring:
  datasource:
    user-management:
      url: jdbc:mysql://localhost:3306/user_management
      username: root
      password: 123456
      driverClassName: com.mysql.cj.jdbc.Driver
      max-active: 500
      max-idle: 20
      initial-size: 20
logging:
  level:
    root: "info"
    web: "debug"
    sql: "error"
    com:
      ying: INFO
jwt:
  secret: j9*L^_ghfADYmhPV=RZg+YD%gG=a#VHG
  expireInHour: 24
  issuer: com.ying.user-management
  acceptExpiresInSecond: 10