package com.ying.msusermanagement.controller;

public interface SwaggerDocConstant {

  String GET_USER_REQUEST_BODY = "";
  String GET_USER_RESPONSE_BODY = "{\n"
      + "    \"id\": 1,\n"
      + "    \"fullName\": \"Ying Sun\",\n"
      + "    \"email\": \"ying@email.com\",\n"
      + "    \"gender\": \"male\",\n"
      + "    \"birthday\": \"2016-01-25T00:00:00.000+00:00\",\n"
      + "    \"createdAt\": \"2022-02-22T01:56:48.571+00:00\",\n"
      + "    \"updatedAt\": \"2022-02-22T01:56:48.571+00:00\",\n"
      + "    \"userCredentials\": [\n"
      + "        {\n"
      + "            \"id\": 1,\n"
      + "            \"userId\": \"1\",\n"
      + "            \"credentialType\": \"email\",\n"
      + "            \"credentialId\": \"ying@email.com\",\n"
      + "            \"status\": \"enabled\",\n"
      + "            \"createdAt\": \"2022-02-22T01:56:48.803+00:00\",\n"
      + "            \"updatedAt\": \"2022-02-22T01:56:48.803+00:00\"\n"
      + "        }\n"
      + "    ],\n"
      + "    \"roles\": [\n"
      + "        {\n"
      + "            \"id\": 1,\n"
      + "            \"roleName\": \"Super Admin\",\n"
      + "            \"status\": \"enabled\",\n"
      + "            \"createdAt\": \"2022-02-22T02:14:28.952+00:00\",\n"
      + "            \"updatedAt\": \"2022-02-22T02:14:28.952+00:00\",\n"
      + "            \"createdBy\": 1,\n"
      + "            \"permissions\": [\n"
      + "                {\n"
      + "                    \"id\": 1,\n"
      + "                    \"name\": \"USERS_GET_USER\"\n"
      + "                },\n"
      + "                {\n"
      + "                    \"id\": 2,\n"
      + "                    \"name\": \"USERS_GET_ME\"\n"
      + "                },\n"
      + "                {\n"
      + "                    \"id\": 3,\n"
      + "                    \"name\": \"USERS_GET_USER_ROLES\"\n"
      + "                },\n"
      + "                {\n"
      + "                    \"id\": 4,\n"
      + "                    \"name\": \"USERS_GET_ME_ROLES\"\n"
      + "                },\n"
      + "                {\n"
      + "                    \"id\": 5,\n"
      + "                    \"name\": \"USERS_UPDATE_USER_ROLES\"\n"
      + "                },\n"
      + "                {\n"
      + "                    \"id\": 6,\n"
      + "                    \"name\": \"USERS_UPDATE_ME_ROLES\"\n"
      + "                },\n"
      + "                {\n"
      + "                    \"id\": 7,\n"
      + "                    \"name\": \"USERS_UPDATE_USER_PROFILE\"\n"
      + "                },\n"
      + "                {\n"
      + "                    \"id\": 8,\n"
      + "                    \"name\": \"USERS_UPDATE_ME_PROFILE\"\n"
      + "                },\n"
      + "                {\n"
      + "                    \"id\": 9,\n"
      + "                    \"name\": \"USERS_CHANGE_ME_PASSWORD\"\n"
      + "                },\n"
      + "                {\n"
      + "                    \"id\": 10,\n"
      + "                    \"name\": \"USERS_CHANGE_USER_PASSWORD\"\n"
      + "                },\n"
      + "                {\n"
      + "                    \"id\": 11,\n"
      + "                    \"name\": \"USERS_GET_USERS\"\n"
      + "                },\n"
      + "                {\n"
      + "                    \"id\": 12,\n"
      + "                    \"name\": \"ROLES_GET_ROLES\"\n"
      + "                },\n"
      + "                {\n"
      + "                    \"id\": 13,\n"
      + "                    \"name\": \"ROLES_CREATE_ROLE\"\n"
      + "                },\n"
      + "                {\n"
      + "                    \"id\": 14,\n"
      + "                    \"name\": \"ROLES_UPDATE_ROLE\"\n"
      + "                },\n"
      + "                {\n"
      + "                    \"id\": 15,\n"
      + "                    \"name\": \"ROLES_DELETE_ROLE\"\n"
      + "                }\n"
      + "            ]\n"
      + "        }\n"
      + "    ]\n"
      + "}";

  String CREATE_USER_REQUEST_BODY = "{\n"
      + "    \"fullName\": \"Ying Sun 1\",\n"
      + "    \"email\": \"ying1@email.com\",\n"
      + "    \"gender\": \"male\",\n"
      + "    \"birthday\": \"2016-01-25T00:00:00.000+00:00\",\n"
      + "    \"userCredentials\": [\n"
      + "        {\n"
      + "            \"credentialType\": \"email\",\n"
      + "            \"credentialId\": \"ying1@email.com\",\n"
      + "            \"password\": \"123456\"\n"
      + "        }\n"
      + "    ],\n"
      + "    \"roles\": [\n"
      + "        {\n"
      + "            \"id\": 1\n"
      + "        }\n"
      + "    ]\n"
      + "}";
  String CREATE_USER_RESPONSE_BODY = "{\n"
      + "    \"id\": 3,\n"
      + "    \"fullName\": \"Ying Sun 1\",\n"
      + "    \"email\": \"ying1@email.com\",\n"
      + "    \"gender\": \"male\",\n"
      + "    \"birthday\": \"2016-01-25T00:00:00.000+00:00\",\n"
      + "    \"createdAt\": \"2022-02-22T23:08:52.150+00:00\",\n"
      + "    \"updatedAt\": \"2022-02-22T23:08:52.150+00:00\",\n"
      + "    \"userCredentials\": [\n"
      + "        {\n"
      + "            \"id\": 2,\n"
      + "            \"userId\": \"3\",\n"
      + "            \"credentialType\": \"email\",\n"
      + "            \"credentialId\": \"ying1@email.com\",\n"
      + "            \"status\": \"enabled\",\n"
      + "            \"createdAt\": \"2022-02-22T23:08:52.181+00:00\",\n"
      + "            \"updatedAt\": \"2022-02-22T23:08:52.181+00:00\"\n"
      + "        }\n"
      + "    ],\n"
      + "    \"roles\": [\n"
      + "        {\n"
      + "            \"id\": 1\n"
      + "        }\n"
      + "    ]\n"
      + "}";

  String AUTHENTICATE_USER_REQUEST_BODY = "{\n"
      + "    \"credentialType\": \"email\",\n"
      + "    \"credentialId\": \"ying@email.com\",\n"
      + "    \"password\": \"123456\"\n"
      + "}";
  String AUTHENTICATE_USER_RESPONSE_BODY = "{\n"
      + "    \"id\": 1,\n"
      + "    \"fullName\": \"Ying Sun\",\n"
      + "    \"email\": \"ying@email.com\",\n"
      + "    \"gender\": \"male\",\n"
      + "    \"birthday\": \"2016-01-25T00:00:00.000+00:00\",\n"
      + "    \"createdAt\": \"2022-02-22T01:56:48.571+00:00\",\n"
      + "    \"updatedAt\": \"2022-02-22T01:56:48.571+00:00\",\n"
      + "    \"userCredentials\": [\n"
      + "        {\n"
      + "            \"id\": 1,\n"
      + "            \"userId\": \"1\",\n"
      + "            \"credentialType\": \"email\",\n"
      + "            \"credentialId\": \"ying@email.com\",\n"
      + "            \"status\": \"enabled\",\n"
      + "            \"createdAt\": \"2022-02-22T01:56:48.803+00:00\",\n"
      + "            \"updatedAt\": \"2022-02-22T01:56:48.803+00:00\"\n"
      + "        }\n"
      + "    ],\n"
      + "    \"roles\": [\n"
      + "        {\n"
      + "            \"id\": 1,\n"
      + "            \"roleName\": \"Super Admin\",\n"
      + "            \"status\": \"enabled\",\n"
      + "            \"createdAt\": \"2022-02-22T02:14:28.952+00:00\",\n"
      + "            \"updatedAt\": \"2022-02-22T02:14:28.952+00:00\",\n"
      + "            \"createdBy\": 1,\n"
      + "            \"permissions\": [\n"
      + "                {\n"
      + "                    \"id\": 1,\n"
      + "                    \"name\": \"USERS_GET_USER\"\n"
      + "                },\n"
      + "                {\n"
      + "                    \"id\": 2,\n"
      + "                    \"name\": \"USERS_GET_ME\"\n"
      + "                },\n"
      + "                {\n"
      + "                    \"id\": 3,\n"
      + "                    \"name\": \"USERS_GET_USER_ROLES\"\n"
      + "                },\n"
      + "                {\n"
      + "                    \"id\": 4,\n"
      + "                    \"name\": \"USERS_GET_ME_ROLES\"\n"
      + "                },\n"
      + "                {\n"
      + "                    \"id\": 5,\n"
      + "                    \"name\": \"USERS_UPDATE_USER_ROLES\"\n"
      + "                },\n"
      + "                {\n"
      + "                    \"id\": 6,\n"
      + "                    \"name\": \"USERS_UPDATE_ME_ROLES\"\n"
      + "                },\n"
      + "                {\n"
      + "                    \"id\": 7,\n"
      + "                    \"name\": \"USERS_UPDATE_USER_PROFILE\"\n"
      + "                },\n"
      + "                {\n"
      + "                    \"id\": 8,\n"
      + "                    \"name\": \"USERS_UPDATE_ME_PROFILE\"\n"
      + "                },\n"
      + "                {\n"
      + "                    \"id\": 9,\n"
      + "                    \"name\": \"USERS_CHANGE_ME_PASSWORD\"\n"
      + "                },\n"
      + "                {\n"
      + "                    \"id\": 10,\n"
      + "                    \"name\": \"USERS_CHANGE_USER_PASSWORD\"\n"
      + "                },\n"
      + "                {\n"
      + "                    \"id\": 11,\n"
      + "                    \"name\": \"USERS_GET_USERS\"\n"
      + "                },\n"
      + "                {\n"
      + "                    \"id\": 12,\n"
      + "                    \"name\": \"ROLES_GET_ROLES\"\n"
      + "                },\n"
      + "                {\n"
      + "                    \"id\": 13,\n"
      + "                    \"name\": \"ROLES_CREATE_ROLE\"\n"
      + "                },\n"
      + "                {\n"
      + "                    \"id\": 14,\n"
      + "                    \"name\": \"ROLES_UPDATE_ROLE\"\n"
      + "                },\n"
      + "                {\n"
      + "                    \"id\": 15,\n"
      + "                    \"name\": \"ROLES_DELETE_ROLE\"\n"
      + "                }\n"
      + "            ]\n"
      + "        }\n"
      + "    ],\n"
      + "    \"accessToken\": \"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJjb20ueWluZy51c2VyLW1hbmFnZW1lbnQiLCJVU0VSX0lEIjoiMSIsIkNSRURFTlRJQUxfSUQiOiJ5aW5nQGVtYWlsLmNvbSIsIkNSRURFTlRJQUxfVFlQRSI6ImVtYWlsIiwiZXhwIjoxNjQ1NjU3NzY4fQ.M0L0xEX7QtEz6iKSgS5n6I3Lswt8iFGHegoAtNcrwpY\"\n"
      + "}";

  String GET_USER_ROLES_REQUEST_BODY = "";
  String GET_USER_ROLES_RESPONSE_BODY = "[\n"
      + "    {\n"
      + "        \"id\": 1,\n"
      + "        \"roleName\": \"Super Admin\",\n"
      + "        \"status\": \"enabled\",\n"
      + "        \"createdAt\": \"2022-02-22T02:14:28.952+00:00\",\n"
      + "        \"updatedAt\": \"2022-02-22T02:14:28.952+00:00\",\n"
      + "        \"createdBy\": 1,\n"
      + "        \"permissions\": [\n"
      + "            {\n"
      + "                \"id\": 1,\n"
      + "                \"name\": \"USERS_GET_USER\"\n"
      + "            },\n"
      + "            {\n"
      + "                \"id\": 2,\n"
      + "                \"name\": \"USERS_GET_ME\"\n"
      + "            },\n"
      + "            {\n"
      + "                \"id\": 3,\n"
      + "                \"name\": \"USERS_GET_USER_ROLES\"\n"
      + "            },\n"
      + "            {\n"
      + "                \"id\": 4,\n"
      + "                \"name\": \"USERS_GET_ME_ROLES\"\n"
      + "            },\n"
      + "            {\n"
      + "                \"id\": 5,\n"
      + "                \"name\": \"USERS_UPDATE_USER_ROLES\"\n"
      + "            },\n"
      + "            {\n"
      + "                \"id\": 6,\n"
      + "                \"name\": \"USERS_UPDATE_ME_ROLES\"\n"
      + "            },\n"
      + "            {\n"
      + "                \"id\": 7,\n"
      + "                \"name\": \"USERS_UPDATE_USER_PROFILE\"\n"
      + "            },\n"
      + "            {\n"
      + "                \"id\": 8,\n"
      + "                \"name\": \"USERS_UPDATE_ME_PROFILE\"\n"
      + "            },\n"
      + "            {\n"
      + "                \"id\": 9,\n"
      + "                \"name\": \"USERS_CHANGE_ME_PASSWORD\"\n"
      + "            },\n"
      + "            {\n"
      + "                \"id\": 10,\n"
      + "                \"name\": \"USERS_CHANGE_USER_PASSWORD\"\n"
      + "            },\n"
      + "            {\n"
      + "                \"id\": 11,\n"
      + "                \"name\": \"USERS_GET_USERS\"\n"
      + "            },\n"
      + "            {\n"
      + "                \"id\": 12,\n"
      + "                \"name\": \"ROLES_GET_ROLES\"\n"
      + "            },\n"
      + "            {\n"
      + "                \"id\": 13,\n"
      + "                \"name\": \"ROLES_CREATE_ROLE\"\n"
      + "            },\n"
      + "            {\n"
      + "                \"id\": 14,\n"
      + "                \"name\": \"ROLES_UPDATE_ROLE\"\n"
      + "            },\n"
      + "            {\n"
      + "                \"id\": 15,\n"
      + "                \"name\": \"ROLES_DELETE_ROLE\"\n"
      + "            }\n"
      + "        ]\n"
      + "    }\n"
      + "]";

  String UPDATE_USER_ROLES_REQUEST_BODY =
        "[\n"
      + "    {\n"
      + "        \"id\": 2\n"
      + "    }\n"
      + "]";
  String UPDATE_USER_ROLES_RESPONSE_BODY = "";

  String UPDATE_USER_PROFILE_REQUEST_BODY =
        "{\n"
      + "    \"fullName\": \"Ying Sun 32\"\n"
      + "}";
  String UPDATE_USER_PROFILE_RESPONSE_BODY =
        "{\n"
      + "    \"id\": 3,\n"
      + "    \"fullName\": \"Ying Sun 32\",\n"
      + "    \"email\": \"ying1@email.com\",\n"
      + "    \"gender\": \"male\",\n"
      + "    \"birthday\": \"2016-01-25T00:00:00.000+00:00\",\n"
      + "    \"createdAt\": \"2022-02-22T23:08:52.150+00:00\",\n"
      + "    \"updatedAt\": \"2022-02-22T23:20:08.826+00:00\"\n"
      + "}";

  String CHANGE_USER_PASSWORD_REQUEST_BODY =
        "{\n"
      + "    \"credentialType\": \"email\",\n"
      + "    \"credentialId\": \"ying@email.com\",\n"
      + "    \"password\": \"123456\"\n"
      + "}";
  String CHANGE_USER_PASSWORD_RESPONSE_BODY = "";

  String GET_USERS_REQUEST_BODY = "";
  String GET_USERS_RESPONSE_BODY =
        "[\n"
      + "    {\n"
      + "        \"id\": 1,\n"
      + "        \"fullName\": \"Ying Sun\",\n"
      + "        \"email\": \"ying@email.com\",\n"
      + "        \"gender\": \"male\",\n"
      + "        \"birthday\": \"2016-01-25T00:00:00.000+00:00\",\n"
      + "        \"createdAt\": \"2022-02-22T01:56:48.571+00:00\",\n"
      + "        \"updatedAt\": \"2022-02-22T01:56:48.571+00:00\"\n"
      + "    },\n"
      + "    {\n"
      + "        \"id\": 3,\n"
      + "        \"fullName\": \"Ying Sun 32\",\n"
      + "        \"email\": \"ying1@email.com\",\n"
      + "        \"gender\": \"male\",\n"
      + "        \"birthday\": \"2016-01-25T00:00:00.000+00:00\",\n"
      + "        \"createdAt\": \"2022-02-22T23:08:52.150+00:00\",\n"
      + "        \"updatedAt\": \"2022-02-22T23:20:08.826+00:00\"\n"
      + "    }\n"
      + "]";

  String GET_ROLES_REQUEST_BODY = "";
  String GET_ROLES_RESPONSE_BODY =
        "[\n"
      + "    {\n"
      + "        \"id\": 1,\n"
      + "        \"roleName\": \"Super Admin\",\n"
      + "        \"status\": \"enabled\",\n"
      + "        \"createdAt\": \"2022-02-22T02:14:28.952+00:00\",\n"
      + "        \"updatedAt\": \"2022-02-22T02:14:28.952+00:00\",\n"
      + "        \"createdBy\": 1,\n"
      + "        \"permissions\": [\n"
      + "            {\n"
      + "                \"id\": 1,\n"
      + "                \"name\": \"USERS_GET_USER\"\n"
      + "            },\n"
      + "            {\n"
      + "                \"id\": 2,\n"
      + "                \"name\": \"USERS_GET_ME\"\n"
      + "            },\n"
      + "            {\n"
      + "                \"id\": 3,\n"
      + "                \"name\": \"USERS_GET_USER_ROLES\"\n"
      + "            },\n"
      + "            {\n"
      + "                \"id\": 4,\n"
      + "                \"name\": \"USERS_GET_ME_ROLES\"\n"
      + "            },\n"
      + "            {\n"
      + "                \"id\": 5,\n"
      + "                \"name\": \"USERS_UPDATE_USER_ROLES\"\n"
      + "            },\n"
      + "            {\n"
      + "                \"id\": 6,\n"
      + "                \"name\": \"USERS_UPDATE_ME_ROLES\"\n"
      + "            },\n"
      + "            {\n"
      + "                \"id\": 7,\n"
      + "                \"name\": \"USERS_UPDATE_USER_PROFILE\"\n"
      + "            },\n"
      + "            {\n"
      + "                \"id\": 8,\n"
      + "                \"name\": \"USERS_UPDATE_ME_PROFILE\"\n"
      + "            },\n"
      + "            {\n"
      + "                \"id\": 9,\n"
      + "                \"name\": \"USERS_CHANGE_ME_PASSWORD\"\n"
      + "            },\n"
      + "            {\n"
      + "                \"id\": 10,\n"
      + "                \"name\": \"USERS_CHANGE_USER_PASSWORD\"\n"
      + "            },\n"
      + "            {\n"
      + "                \"id\": 11,\n"
      + "                \"name\": \"USERS_GET_USERS\"\n"
      + "            },\n"
      + "            {\n"
      + "                \"id\": 12,\n"
      + "                \"name\": \"ROLES_GET_ROLES\"\n"
      + "            },\n"
      + "            {\n"
      + "                \"id\": 13,\n"
      + "                \"name\": \"ROLES_CREATE_ROLE\"\n"
      + "            },\n"
      + "            {\n"
      + "                \"id\": 14,\n"
      + "                \"name\": \"ROLES_UPDATE_ROLE\"\n"
      + "            },\n"
      + "            {\n"
      + "                \"id\": 15,\n"
      + "                \"name\": \"ROLES_DELETE_ROLE\"\n"
      + "            }\n"
      + "        ]\n"
      + "    }\n"
      + "]";

  String CREATE_ROLE_REQUEST_BODY =
        "{\n"
      + "    \"roleName\": \"End User\",\n"
      + "    \"description\": \"End user description\",\n"
      + "    \"permissions\": [\n"
      + "        {\n"
      + "            \"id\": 1\n"
      + "        },\n"
      + "        {\n"
      + "            \"id\": 2\n"
      + "        },\n"
      + "        {\n"
      + "            \"id\": 3\n"
      + "        }\n"
      + "    ]\n"
      + "}";
  String CREATE_ROLE_RESPONSE_BODY = "{\n"
      + "    \"id\": 4,\n"
      + "    \"roleName\": \"End User\",\n"
      + "    \"description\": \"End user description\",\n"
      + "    \"status\": \"enabled\",\n"
      + "    \"createdAt\": \"2022-02-22T23:22:43.159+00:00\",\n"
      + "    \"updatedAt\": \"2022-02-22T23:22:43.159+00:00\",\n"
      + "    \"createdBy\": 1,\n"
      + "    \"permissions\": [\n"
      + "        {\n"
      + "            \"id\": 1\n"
      + "        },\n"
      + "        {\n"
      + "            \"id\": 2\n"
      + "        },\n"
      + "        {\n"
      + "            \"id\": 3\n"
      + "        }\n"
      + "    ]\n"
      + "}";

  String UPDATE_ROLE_REQUEST_BODY =
        "{\n"
      + "    \"status\": \"enabled\",\n"
      + "    \"permissions\": [\n"
      + "        {\n"
      + "            \"id\": 3\n"
      + "        }\n"
      + "    ]\n"
      + "}";
  String UPDATE_ROLE_RESPONSE_BODY =
        "{\n"
      + "    \"id\": 4,\n"
      + "    \"roleName\": \"End User\",\n"
      + "    \"description\": \"End user description\",\n"
      + "    \"status\": \"enabled\",\n"
      + "    \"createdAt\": \"2022-02-22T23:22:43.159+00:00\",\n"
      + "    \"updatedAt\": \"2022-02-22T23:23:25.986+00:00\",\n"
      + "    \"createdBy\": 1\n"
      + "}";

  String DELETE_ROLE_REQUEST_BODY = "";
  String DELETE_ROLE_RESPONSE_BODY =
        "{\n"
      + "    \"id\": 4,\n"
      + "    \"roleName\": \"End User\",\n"
      + "    \"description\": \"End user description\",\n"
      + "    \"status\": \"enabled\",\n"
      + "    \"createdAt\": \"2022-02-22T23:22:43.159+00:00\",\n"
      + "    \"updatedAt\": \"2022-02-22T23:23:25.986+00:00\",\n"
      + "    \"createdBy\": 1,\n"
      + "    \"permissions\": []\n"
      + "}";
}
